/**
 * ETF catalog — committed cross-repo mirror of `Funds_DAG/configs/etf_universe.yaml`.
 *
 * The single source of truth is the YAML in Funds_DAG; we mirror it as
 * `mcp/data/etf_master.json` (generated by
 * `Funds_DAG/scripts/export_etf_master_json.py`, same cross-repo pattern as
 * benchmark_master.json). This module loads the JSON at first use and caches
 * it for the lifetime of the Node process — the ETF universe changes rarely
 * and a redeploy is required anyway, so a one-time read is the right
 * complexity ceiling. Empty / missing file → empty catalog (degrades to
 * "search returns nothing"), never throws.
 *
 * MASTER_BACKLOG D.9 follow-up #2.
 */

import { existsSync, readFileSync } from "fs";
import { join } from "path";

export interface EtfEntryRecord {
  bw_etf_id: string;
  ticker: string;
  name: string;
}

interface EtfCatalog {
  schema_version: string;
  n_entries: number;
  /** ticker_lower → bw_etf_id */
  aliases: Record<string, string>;
  /** bw_etf_id → entry record */
  entries: Record<string, EtfEntryRecord>;
}

const EMPTY: EtfCatalog = {
  schema_version: "etf-master/2.0",
  n_entries: 0,
  aliases: {},
  entries: {},
};

let _cached: EtfCatalog | null = null;

function _path(): string {
  return join(process.cwd(), "mcp", "data", "etf_master.json");
}

function _load(): EtfCatalog {
  if (_cached) return _cached;
  const p = _path();
  if (!existsSync(p)) {
    _cached = EMPTY;
    return _cached;
  }
  try {
    const parsed = JSON.parse(readFileSync(p, "utf-8")) as Partial<EtfCatalog>;
    _cached = {
      schema_version: parsed.schema_version ?? EMPTY.schema_version,
      n_entries: parsed.n_entries ?? Object.keys(parsed.entries ?? {}).length,
      aliases: parsed.aliases ?? {},
      entries: (parsed.entries ?? {}) as Record<string, EtfEntryRecord>,
    };
    return _cached;
  } catch {
    _cached = EMPTY;
    return _cached;
  }
}

/** Test seam: reload the cached catalog from disk. */
export function _reloadEtfCatalog(): EtfCatalog {
  _cached = null;
  return _load();
}

/** Resolve a ticker (case-insensitive) to a `bw_etf_id`, or null if unknown. */
export function lookupEtfTicker(input: string): string | null {
  const cat = _load();
  const key = (input ?? "").trim().toLowerCase();
  if (!key) return null;
  return cat.aliases[key] ?? null;
}

/** Read the full entry record for a `bw_etf_id`, or null. */
export function getEtfEntry(bwEtfId: string): EtfEntryRecord | null {
  return _load().entries[bwEtfId.toUpperCase()] ?? null;
}

/** All known entries (ordered by `bw_etf_id`). */
export function listEtfEntries(): EtfEntryRecord[] {
  return Object.values(_load().entries);
}

export interface EtfSearchHit extends EtfEntryRecord {
  /** Higher = better match. Useful for callers that want to merge with their own ranking. */
  score: number;
}

/**
 * Substring + prefix search over ticker / name.
 *
 * Ranking (higher = better):
 *   100  exact ticker match
 *    70  ticker prefix match
 *    50  ticker substring
 *    40  name word-boundary prefix
 *    30  name substring
 *
 * Empty query returns all entries (ordered by ticker, capped at `limit`).
 * `limit` is clamped to [1, 100]; default 25.
 */
export function searchEtfs(query: string, limit = 25): EtfSearchHit[] {
  const cat = _load();
  const all = Object.values(cat.entries);
  const safeLimit = Math.min(Math.max(limit, 1), 100);

  const q = (query ?? "").trim().toLowerCase();
  if (!q) {
    return [...all]
      .sort((a, b) => a.ticker.localeCompare(b.ticker))
      .slice(0, safeLimit)
      .map((e) => ({ ...e, score: 0 }));
  }

  const hits: EtfSearchHit[] = [];
  for (const e of all) {
    const ticker = e.ticker.toLowerCase();
    const name = e.name.toLowerCase();

    let score = 0;
    if (ticker === q) score = 100;
    else if (ticker.startsWith(q)) score = 70;
    else if (ticker.includes(q)) score = 50;
    else if (
      name === q ||
      name.startsWith(`${q} `) ||
      name.split(/[\s&-]+/).some((w) => w === q || w.startsWith(q))
    )
      score = 40;
    else if (name.includes(q)) score = 30;

    if (score > 0) hits.push({ ...e, score });
  }

  hits.sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    return a.ticker.localeCompare(b.ticker);
  });

  return hits.slice(0, safeLimit);
}

/** Currently-loaded catalog metadata — useful for diagnostics endpoints. */
export function etfCatalogMetadata(): {
  schema_version: string;
  n_entries: number;
  path: string;
} {
  const cat = _load();
  return { schema_version: cat.schema_version, n_entries: cat.n_entries, path: _path() };
}
