/**
 * Pins the SDK's Python port (sdk/riskmodels/exposure_history.py) to this
 * implementation. Inputs and expected outputs live in one fixture that both
 * test suites read. Regenerate after an intended change with:
 *   UPDATE_PARITY=1 npx vitest run tests/signed-exposure-parity.test.ts
 */
import * as fs from "fs";
import * as path from "path";
import { describe, expect, it } from "vitest";
import { computeSignedExposure, type Basis, type StockInput } from "@/lib/portfolio/signed-exposure";

const FIXTURE = path.join(process.cwd(), "sdk/tests/fixtures/signed_exposure_parity.json");

const ETFS = ["SPY", "XLK", "SMH", "XLF", "KBE"];
const S = [
  [1.0e-4, 1.1e-4, 1.3e-4, 0.9e-4, 1.0e-4],
  [1.1e-4, 1.6e-4, 1.8e-4, 0.8e-4, 0.9e-4],
  [1.3e-4, 1.8e-4, 3.0e-4, 0.9e-4, 1.0e-4],
  [0.9e-4, 0.8e-4, 0.9e-4, 1.4e-4, 1.6e-4],
  [1.0e-4, 0.9e-4, 1.0e-4, 1.6e-4, 2.2e-4],
];
const m = (o: Record<string, number | null>) => o;
const STOCKS: StockInput[] = [
  { symbol: "S-NVDA", tickers: ["NVDA"], value: 220_000, sector_etf: "XLK", subsector_etf: "SMH",
    metrics: m({ l1_mkt_beta: 1.8, l1_mkt_hr: -1.8, l2_mkt_hr: -0.9, l2_sec_hr: -0.8, l3_mkt_hr: -0.5, l3_sec_hr: -0.4, l3_sub_hr: -0.7, stock_var: 9e-4, l1_res_er: 0.6, l2_res_er: 0.5, l3_res_er: 0.4, lstar_level: 3 }) },
  { symbol: "S-AMD", tickers: ["AMD"], value: -130_000, sector_etf: "XLK", subsector_etf: "SMH",
    metrics: m({ l1_mkt_beta: 2.0, l1_mkt_hr: -2.0, l2_mkt_hr: -1.0, l2_sec_hr: -0.9, l3_mkt_hr: -0.6, l3_sec_hr: -0.3, l3_sub_hr: -0.9, stock_var: 1.2e-3, l1_res_er: 0.7, l2_res_er: 0.55, l3_res_er: 0.5, lstar_level: 2 }) },
  { symbol: "S-JPM", tickers: ["JPM"], value: 90_000, sector_etf: "XLF", subsector_etf: "KBE",
    metrics: m({ l1_mkt_beta: 1.1, l1_mkt_hr: -1.1, l2_mkt_hr: -0.6, l2_sec_hr: -0.5, l3_mkt_hr: -0.5, l3_sec_hr: -0.2, l3_sub_hr: -0.3, stock_var: 4e-4, l1_res_er: 0.5, l2_res_er: 0.42, l3_res_er: 0.4, lstar_level: 1 }) },
  { symbol: "S-THIN", tickers: ["THIN"], value: -40_000, sector_etf: "XLF", subsector_etf: null,
    metrics: m({ l1_mkt_beta: null, l1_mkt_hr: null, stock_var: null, lstar_level: null }) },
  { symbol: "S-BAD", tickers: ["BAD"], value: 15_000, sector_etf: "XLK", subsector_etf: null,
    metrics: m({ l1_mkt_beta: 1.2, l1_mkt_hr: -1.2, l3_mkt_hr: -0.7, l3_sec_hr: -0.4, l3_sub_hr: -0.1, stock_var: 5e-4, l1_res_er: 1.4, l3_res_er: 1.3, lstar_level: 1 }) },
];
const DIRECT = [{ ticker: "SPY", value: -60_000 }, { ticker: "XLF", value: 25_000 }];
const GROSS = [...STOCKS, ...DIRECT].reduce((a, s) => a + Math.abs(s.value), 0);

function expectedFor(basis: Basis) {
  const out: any = computeSignedExposure({
    stocks: STOCKS, directEtfs: DIRECT, inputGrossUsd: GROSS, basis,
    cov: { etfs: ETFS, S, start: null, end: null, requested_n: 252, effective_n: 252 },
  });
  const hedge = basis === "lstar" ? out.hedges.lstar : out.hedges[basis];
  return {
    stock_beta_usd: out.beta.stock_beta_usd,
    direct_etf_beta_usd: out.beta.direct_etf_beta_usd,
    total_beta_usd: out.beta.total_beta_usd,
    stock_hedge_trade_usd: hedge.stock_hedge_trade_usd,
    total_neutralizing_trade_usd: hedge.total_neutralizing_trade_usd,
    names_by_level: out.risk.names_by_level,
    excluded_from_lstar: out.coverage.excluded_from_lstar.map((e: any) => [e.ticker, e.reason]),
    residual_flagged: out.coverage.residual_flagged.map((e: any) => e.ticker),
    systematic_daily_variance: out.risk.systematic.daily_variance_usd2,
    residual_daily_variance: out.risk.residual.daily_variance_usd2,
    layer_contributions: Object.fromEntries(
      Object.entries(out.risk.systematic.layer_contributions).map(([k, v]: any) => [k, v.daily_variance_usd2]),
    ),
    total_annual_vol_usd: out.risk.total.annual_vol_usd,
    coverage_total_risk: out.coverage.by_calculation.total_risk,
  };
}

describe("signed exposure parity fixture", () => {
  it("matches the stored expected outputs (shared with the SDK tests)", () => {
    const fixture = {
      note: "Generated by tests/signed-exposure-parity.test.ts. Shared by sdk/tests/test_exposure_history.py.",
      inputs: { etfs: ETFS, S, stocks: STOCKS, direct_etfs: DIRECT, input_gross_usd: GROSS },
      expected: { lstar: expectedFor("lstar"), l1: expectedFor("l1"), l3: expectedFor("l3") },
    };
    if (process.env.UPDATE_PARITY === "1" || !fs.existsSync(FIXTURE)) {
      fs.writeFileSync(FIXTURE, JSON.stringify(fixture, null, 1) + "\n");
    }
    expect(JSON.parse(fs.readFileSync(FIXTURE, "utf8"))).toEqual(JSON.parse(JSON.stringify(fixture)));
  });
});
